package db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

public class DbConnect {
	private final String USERNAME = "root";
	private final String PASSWORD = "";
	private final String DATABASE = "govlashlaundry";
	private final String HOST = "localhost:3306";
	private final String CONNECTION = String.format("jdbc:mysql://%s/%s", HOST, DATABASE);
	
	public ResultSet rs;
	public ResultSetMetaData rsm;
	
	private Connection con;
	private Statement st;
	private static DbConnect connect;
	
	// singleton
	public static DbConnect getInstance() {
		if(connect == null) connect = new DbConnect();
		return connect;
	}
	
	// untuk connect ke database local
	private DbConnect() {
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			
			con = DriverManager.getConnection(CONNECTION, USERNAME, PASSWORD);
			st = con.createStatement();
			
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	// get data
	public ResultSet execQuery(String query) {
		try {
			rs = st.executeQuery(query);
			rsm = rs.getMetaData();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return rs;
	}
	
	// modifying data
	public void execUpdate(String query) {
		try {
			st.executeUpdate(query);
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	// untuk query operation
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
	    return con.prepareStatement(sql, autoGeneratedKeys);
	}

	// query operation juga, tapi untuk id baru
	public PreparedStatement prepareStatement(String sql) throws SQLException {
	    return con.prepareStatement(sql);
	}
}
